### ISSUE TITLE
Automate updating database data

### ISSUE THREAD

**Issue by korikuzma** [cancervariants/gene-normalization#129]
Our process for updating the database is not ideal. We nuke the database, then have to manually run the CLI commands to re-load and create merged concepts. We should consider creating deltas and updating the database accordingly

**Comment by jsstevenson** [comment]
+ automate generation of new DB dumps on S3, too

**Comment by jsstevenson** [comment]
I think this is the same as #58 and there's a bit more discussion there so I'm closing this
