### ISSUE TITLE
Database endpoint usage feedback

### ISSUE THREAD

**Issue by jsstevenson** [cancervariants/gene-normalization#217]
It's probably nonstandard behavior to always print feedback to the console about the currently-used database endpoint when the connection is created. I tentatively think we should be making a `logging` call instead. We could also make an optional `verbose` mode or something, too, but that would be more work.

**Comment by korikuzma** [comment]
Personally, I like this when connected to AWS instance (by accident). So then I can immediately stop when I see that it's not using local when it should be

**Comment by jsstevenson** [comment]
Yeah, I think retaining a notification is helpful in some cases (maybe some commands more than others) but I think there are good reasons to provide verbosity/quiet options, maybe with silence as a default -- see eg http://www.linfo.org/rule_of_silence.html (I think the bit about leaving output minimal by default unless it's something that might need to be piped is good).

**Comment by jsstevenson** [comment]
Strictly speaking, this is done as of #299 but I don't believe that branch is merged to main yet
