### ISSUE TITLE
Pass DB URL as CLI parameter

### ISSUE THREAD

**Issue by jsstevenson** [cancervariants/gene-normalization#240]
It isn't super important, but implementing this would be easy and might make instructions simpler.

**Comment by korikuzma** [comment]
Is this different than this?
https://github.com/cancervariants/gene-normalization/blob/f7bf5b49d030ac69dd78299cca6fdce5d41fa7c1/gene/cli.py#L27

**Comment by jsstevenson** [comment]
...no, no it is not
