### ISSUE TITLE
Capture previous gene identifiers from NCBI

### ISSUE THREAD

**Issue by ahwagner** [cancervariants/gene-normalization#26]
NCBI has retired gene identifiers in the past, e.g.:

- [ncbigene:401317](https://www.ncbi.nlm.nih.gov/gene/401317) now maps to [ncbigene:9586](https://www.ncbi.nlm.nih.gov/gene/9586). Our normalizer should match the old ID to the current record. This should be treated analogous to the "previous symbols" attribute in HGNC.
- [ncbigene:103344718](https://www.ncbi.nlm.nih.gov/gene/103344718) is a _discontinued_ gene. We should normalize to concepts like this, but also have a status attribute that makes it clear this is no longer considered a gene. We should also emit a warning in our `warnings` attribute for each such entry, akin to: `ncbigene:103344718 is a discontinued gene concept.`

**Comment by korikuzma** [comment]
For the first point, we should discuss how often we should be updating NCBI. The `gene_history` file we use for `previous_symbols` is recalculated daily and we had downloaded this on 01/15/2021.

**Comment by korikuzma** [comment]
Getting back to this, it doesn't look like NCBI has any data for discontinued genes other than `symbol` and `id`. I emailed support to see if I am missing where to find information like `chromosome` and `map location` so that we can normalize these concepts.
