### ISSUE TITLE
Clean up console feedback and logging

### ISSUE THREAD

**Issue by jsstevenson** [cancervariants/gene-normalization#298]
It'd be good to look at how this is done with fresh eyes and make sure it's consistent/comprehensive. I think the ETL and DB methods should take a `silent` param, the CLI should always roll with `silent=False`, and we can think a bit about what default behavior should be outside of the CLI.

Most likely need to implement `wags-tails` before getting this done.

**Comment by korikuzma** [comment]
@jsstevenson I think this is complete. Is there anything else todo before we close?
